server:
  port: 9091

spring:
  application:
    name: SKILL-SERVICE
  config:
    import: optional:configserver:http://localhost:9296/
  data:
    mongodb:
      uri: mongodb://mongoonbrd:mongoonbrd@docdb-2023-03-23-15-29-47.cluster-c9bnvhq6g6em.ap-south-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=rds-combined-ca-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
      database : test
      ssl:
        enabled: true
        invalidHostNameAllowed: true
        trust-store: /rds-truststore.jks
        trust-store-password: mnbvcxz
    
logging:
  file.name: /tmp/certs/logger/skill-service-app.log