server:
  port: 9091



spring:
  application:
    name: SKILL-SERVICE
  data:
    mongodb:
       uri: mongodb://localhost:27017/?readPreference=primary&ssl=false
       database : myd
#      uri: mongodb://Manideep1:Manideep1@docdb-2023-05-29-07-06-57.czzwddiesvbx.ap-south-1.docdb.amazonaws.com:27017/?ssl=true&ssl_ca_certs=ap-south-1-bundle.pem&retryWrites=false
#      database : mydb
#      ssl:
#        enabled: true
#        invalidHostNameAllowed: true
#        trust-store: /rds-truststore.jks
#        trust-store-password: mnbvcxz
#      
      
#  zipkin:
#    base-url: http://127.0.0.1:9411/
    
logging:
  file.name: C:/Users/002TCO744/Desktop/elk-logs/skill-service.log
  
eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: false
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#department:
#  service:
#    url: http://DEPARTMENT-SERVICE

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url: 
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
   
  